// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.707
package home

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Hello(name string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html lang=\"en\"><script src=\"https://unpkg.com/htmx.org@1.9.12\" integrity=\"sha384-ujb1lZYygJmzgSwoxRggbCHcjc0rB2XoQrxeTUQyRjrOnlCoYta87iKBWq3EsdM2\" crossorigin=\"anonymous\"></script><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><title>LLM POC</title><link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/2.0.2/tailwind.min.css\"><style type=\"text/css\">\n\t\t.btn.htmx-request {\n        display: none;\n    }\n\n    #indicator.htmx-request {\n        display: block;\n    }\n\t</style></head><body><div class=\"flex items-center\"><h3 class=\"font-bold mr-2 font-bold text-gray-500 text-sm uppercase\">EVOLUÇÃO DO RESULTADO CHAVE</h3><span class=\"px-2 py-1 text-sm font-semibold text-white bg-black rounded\">beta</span></div><div x-if=\"summarizedKeyResult\"><div class=\"mt-5\"></div></div><div id=\"generated-text\"><button class=\"loaded-content flex items-center justify-center w-full px-4 py-2 mt-5 border border-pink-500 rounded-md text-pink-500 hover:bg-pink-500        hover:text-white\" hx-post=\"http://localhost:8082/generate\" hx-trigger=\"click\" hx-target=\"#generated-text\" hx-swap=\"innerHTML\" hx-indicator=\"#indicator\" hx-disabled-elt=\"this\" hx-on::before-request=\"this.style.display=&#39;none&#39;\" hx-on::after-request=\"this.style.display=&#39;block&#39;\">Entenda melhor este resultado-chave</button><div id=\"indicator\" class=\"htmx-indicator hidden\"><img src=\"static/images/wand_big.gif\" alt=\"This is a wand icon\"><p class=\"mt-2 text-gray-500\">Escolhendo o melhor baralho para mágica</p></div></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
